# Generated by Django 5.1.6 on 2025-02-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='book/image/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
