# Generated by Django 5.1.1 on 2025-04-16 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_emb'),
        ('recommendations', '0002_alter_bookrating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta')], max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('user', 'book')},
        ),
    ]
