# Generated by Django 5.1.1 on 2025-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrating',
            name='rated_at',
        ),
        migrations.RemoveField(
            model_name='bookrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='bookrating',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
