# Generated by Django 5.1.1 on 2025-04-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_alter_bookrating_unique_together_bookrating_reaction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='bookrating',
            name='reaction',
        ),
    ]
