# Generated by Django 5.1.1 on 2025-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='book/images/')),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=250)),
                ('availability', models.URLField(blank=True)),
            ],
        ),
    ]
