# Generated by Django 5.1.1 on 2025-03-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='availability',
            new_name='url',
        ),
    ]
