# Generated by Django 5.1.1 on 2025-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book/imagenes/default.jpg', upload_to='book/imagenes/'),
        ),
    ]
