# Generated by Django 5.1.1 on 2025-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_images/default_nia.jpg', null=True, upload_to='book_images/'),
        ),
    ]
