# Generated by Django 5.1.1 on 2025-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='emb',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
