# Generated by Django 5.1.1 on 2025-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_book_emb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='emb',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
