# Generated by Django 5.1.1 on 2025-04-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_alter_book_emb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='emb',
        ),
    ]
