# Generated by Django 5.1.1 on 2025-04-17 23:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_alter_book_emb'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookRating',
            new_name='BookRecommendation',
        ),
    ]
