# Generated by Django 5.1.1 on 2025-04-18 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_rename_bookrating_bookrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genres', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('scifi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('romance', 'Romance'), ('selfhelp', 'Self-help and Personal Development')], max_length=20)),
                ('favorite_authors', models.TextField()),
                ('preferred_length', models.CharField(choices=[('short_readings', 'Short reading (less than 50 pages)'), ('medium_readings', 'Medium reading (between 50 and 200 pages)'), ('long_readings', 'Long reading (more than 200 pages)')], max_length=20)),
                ('preferred_era', models.CharField(choices=[('contemporary', 'Contemporary'), ('classic', 'Classic')], max_length=20)),
                ('liked_books', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
