# Generated by Django 5.1.1 on 2025-04-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_bookrating_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRating',
        ),
    ]
