# Generated by Django 5.1.1 on 2025-04-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_era',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_genres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_length',
            field=models.CharField(max_length=100),
        ),
    ]
