# Generated by Django 5.1.1 on 2025-04-16 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_book_emb'),
        ('recommendations', '0006_remove_bookrating_rated_at_remove_bookrating_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('user', 'book')},
        ),
        migrations.AddField(
            model_name='bookrating',
            name='reaction',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎')], default='like', max_length=10),
        ),
        migrations.RemoveField(
            model_name='bookrating',
            name='liked',
        ),
    ]
